### ISSUE TITLE
0.9.0 tag on Docker Hub

### ISSUE THREAD

**Issue by jbergknoff** [expert360/docker-elasticmq#2]
Hi, now that the `latest` tag is on version 0.9.0, please release a `0.9.0` tag on Docker Hub so I can pin the version. Thank you!

**Comment by CerealBoy** [comment]
@jbergknoff Three new tags are now available

* ``0.9.0``
* ``0.9.3``
* ``0.12.1``

I've made a note now as a part of the release process to create tags on hub for on-going release changes.

**Comment by jbergknoff** [comment]
@CerealBoy excellent, thank you!
